-- ─────────────────────────────────────────────────────────────────────────────
-- Tablas creadas en activa-t después del fork de fondo2 (16–21 jul 2026) y que
-- alimentan Informes de Impacto y las secciones II–IV de Inf. Gerencial.
--
-- Solo DDL: los datos llegan por el sync desde Supabase
-- (actualizar_bd_servidor.sh / actualizar_desde_supabase.ps1, que ya las
-- incluyen en su lista de tablas de negocio).
--
-- Uso:
--   docker compose exec -T db psql -U fondo2 -d fondo2 -v ON_ERROR_STOP=1 < scripts/create_tablas_gerenciales.sql
--
-- Idempotente. En el servidor las tres ya existen (llegaron con la carga del
-- 23/24-jul); este script es para entornos nuevos y para el local.
-- ─────────────────────────────────────────────────────────────────────────────

-- Informes de evaluación de impacto (uno o varios por grupo; un mismo PDF puede
-- repetirse en varias filas cuando el informe sirve a varios grupos).
create table if not exists public.informe_impacto (
  id           bigint generated by default as identity primary key,
  grupo_id     integer not null references public.grupo(id),
  linea_id     integer references public.lineas(id),   -- opcional: informe de una línea específica
  titulo       text not null,
  fecha_inicio date not null,                          -- inicio de la evaluación de impacto
  fecha_fin    date,                                   -- presentación del informe (null = en curso)
  archivo_url  text,                                   -- PDF servido por /api/documentos/[archivo]
  created_at   timestamptz not null default now()
);

comment on table public.informe_impacto is
  'Informes de evaluación de impacto por grupo (módulo Catálogos + línea de tiempo de Proyectos)';

-- Saldos bancarios al cierre del ejercicio, POR BANCO (varios por año).
-- Reemplaza al rubro "Saldos en Bancos" de finanzas_anual como fuente del
-- widget de Inf. Gerencial.
create table if not exists public.saldo_bancario (
  id         bigint generated by default as identity primary key,
  año        integer not null,
  banco      text not null,
  monto      numeric not null default 0,
  created_at timestamptz not null default now()
);

comment on table public.saldo_bancario is
  'Saldos bancarios al cierre del ejercicio, desglosados por banco (Inf. Gerencial; edición en Catálogos)';

-- Serie histórica de gastos de proyectos/servicios (EEFF) y cantidad de
-- colaboradores, 1999–2026: sustento de la Sección IV (Análisis).
create table if not exists public.auditoria_eeff_historico (
    anio                      integer primary key,
    gasto_proyectos_servicios numeric not null default 0,
    colaboradores             integer not null default 0,
    categoria                 text    not null,
    proyectado                boolean not null default false
);

comment on table public.auditoria_eeff_historico is
  'Gasto EEFF y colaboradores por año (gráfico de la Sección IV de Inf. Gerencial)';
