-- Tablas portadas de sistema-activa-t (commits 9e4afec, 9932b3d, f3f730a):
-- informe_impacto, saldo_bancario y auditoria_eeff_historico.
-- Los datos llegan por actualizar_desde_supabase.ps1; aquí solo la estructura.
-- Idempotente (create if not exists).

create table if not exists public.informe_impacto (
  id           bigint generated by default as identity primary key,
  grupo_id     integer not null references public.grupo(id),
  linea_id     integer references public.lineas(id),
  titulo       text not null,
  fecha_inicio date not null,
  fecha_fin    date,
  archivo_url  text,
  created_at   timestamptz not null default now()
);

comment on table public.informe_impacto is
  'Informes de evaluación de impacto por grupo (módulo Catálogos + línea de tiempo de Proyectos)';

create table if not exists public.saldo_bancario (
  id         bigint generated by default as identity primary key,
  año        integer not null,
  banco      text not null,
  monto      numeric not null default 0,
  created_at timestamptz not null default now()
);

comment on table public.saldo_bancario is
  'Saldos bancarios al cierre del ejercicio, desglosados por banco (widget de Inf. Gerencial; edición en Catálogos)';

create table if not exists public.auditoria_eeff_historico (
    anio                        integer primary key,
    gasto_proyectos_servicios   numeric  not null default 0,
    colaboradores               integer  not null default 0,
    categoria                   text     not null,
    proyectado                  boolean  not null default false
);
