-- ====================================================================
-- Órdenes de pago de becas (skill pago-becas) — 2026-09-29
--
-- Catálogos:            bancos, concepto_beca, columnas nuevas de institucion
-- Gestión de Servicios: becas_nueva.codigo_convenio/codigo_interno, beca_cuenta,
--                       beca_presupuesto, beca_orden_pago, beca_orden_pago_detalle,
--                       vista v_beca_saldo
--
-- Solo ESTRUCTURA. Los datos (seeds de bancos y conceptos, cuentas, presupuesto,
-- histórico de OP) van en scripts/data_becas_*.sql.
-- Idempotente: se puede aplicar las veces que sea (lo aplica el paso 2b de
-- actualizar_bd_servidor.sh).
--
-- avance_beca NO cambia: el vínculo pago→evento es
-- beca_orden_pago_detalle.avance_beca_id, y el sustento del evento sigue la
-- convención de src/lib/pagos.ts ("OP 205-UPS-AS - S/ 822.26").
-- ====================================================================

-- ─── Catálogos ──────────────────────────────────────────────────────

-- Bancos por el código de 3 dígitos con que empieza el CCI.
create table if not exists public.bancos (
  id         serial primary key,
  codigo_cci char(3) not null unique,
  nombre     text not null,
  sigla      text
);
comment on table public.bancos is
  'Bancos por el código CCI de 3 dígitos (módulo Catálogos; órdenes de pago de becas)';

-- Catálogo único de conceptos de beca. Los Anexo 02 usan códigos distintos por
-- convocatoria (OTR-0001-ACADEMICOS en 2025-II, OTR-0006-ACADEMICOS en 2025-I):
-- todos se registran como alias en codigos_anexo.
create table if not exists public.concepto_beca (
  id                serial primary key,
  codigo            text not null unique,
  nombre            text not null,
  tipo              text not null check (tipo in ('ACADEMICO','NO_ACADEMICO','INCENTIVO','TITULACION')),
  abono_por_defecto text not null check (abono_por_defecto in ('IE','BECARIO')),
  codigos_anexo     text[] not null default '{}',
  activo            boolean not null default true,
  orden             integer
);
comment on table public.concepto_beca is
  'Conceptos de pago de becas; codigos_anexo = alias usados en los Anexo 02 (módulo Catálogos)';

-- Datos de pago de la institución educativa. Con convenio: abono directo a la
-- IE; sin convenio: reembolso al becario. La cuenta contable (4699xxxx) NO va
-- aquí porque cambia por convocatoria: va en la línea de la OP.
alter table public.institucion add column if not exists ruc char(11);
alter table public.institucion add column if not exists tiene_convenio boolean default false;
alter table public.institucion add column if not exists banco_id integer references public.bancos(id);
alter table public.institucion add column if not exists cuenta_bancaria text;
alter table public.institucion add column if not exists cci char(20);
alter table public.institucion add column if not exists cuenta_validada_el date;
alter table public.institucion add column if not exists observacion text;

-- ─── Gestión de Servicios ───────────────────────────────────────────

-- Claves para cruzar con los Excel de Servicios.
alter table public.becas_nueva add column if not exists codigo_convenio text;  -- 'Código 102-2026-FE' → '102-2026-FE'
alter table public.becas_nueva add column if not exists codigo_interno text;   -- 'CU-0007' / 'CT-0018'
create index if not exists becas_nueva_documento_idx on public.becas_nueva (documento);

-- Cuenta del becario o de su aval, con historial (una sola vigente por beca).
create table if not exists public.beca_cuenta (
  id             bigint generated by default as identity primary key,
  beca_id        integer not null references public.becas_nueva(id) on delete cascade,
  titular_tipo   text not null check (titular_tipo in ('BECARIO','AVAL')),
  titular_nombre text not null,
  titular_dni    text not null,
  banco_id       integer references public.bancos(id),
  numero_cuenta  text,
  cci            char(20),
  cci_valido     boolean,
  vigente        boolean not null default true,
  fuente         text,
  desde          date default current_date,
  observacion    text,
  created_at     timestamptz default now()
);
create unique index if not exists beca_cuenta_vigente_uq on public.beca_cuenta (beca_id) where vigente;
create index if not exists beca_cuenta_beca_idx on public.beca_cuenta (beca_id);

-- Presupuesto programado por becario y concepto. Ejecutado y saldo NO se
-- guardan: salen de v_beca_saldo (líneas de OP pagadas).
create table if not exists public.beca_presupuesto (
  id          bigint generated by default as identity primary key,
  beca_id     integer not null references public.becas_nueva(id) on delete cascade,
  concepto_id integer not null references public.concepto_beca(id),
  programado  numeric(14,2) not null default 0,
  tope        numeric(14,2),
  fuente      text,
  updated_at  timestamptz default now(),
  unique (beca_id, concepto_id)
);

-- Cabecera de la orden de pago.
create table if not exists public.beca_orden_pago (
  id                 bigint generated by default as identity primary key,
  codigo             text not null unique,          -- '205-UPS-AS/FE-2026'
  numero             integer not null,              -- 205
  anio               integer not null,              -- 2026
  fecha_emision      date,
  informe_codigo     text,                          -- '209-UPS-AS/FE-2026'
  grupo_id           integer references public.grupo(id),
  linea_id           integer references public.lineas(id),
  modalidad          text check (modalidad in ('ABONO_IE','REEMBOLSO','ABONO_BECARIO')),
  descripcion        text,
  importe            numeric(14,2) not null,
  n_becarios         integer,
  estado             text not null default 'GENERADA'
                     check (estado in ('GENERADA','ENVIADA','EN_TESORERIA','PENDIENTE_FIRMA','PAGADA','OBSERVADA','ANULADA')),
  dia_pago           date,                          -- carpeta DDMMAAAA de pago-Eli
  txt_archivo        text,
  nro_orden_banco    text,
  fecha_ejecucion    date,
  importe_cargado    numeric(14,2),
  carpeta_sharepoint text,
  observaciones      text,
  created_at         timestamptz default now(),
  created_by         text,
  unique (numero, anio)
);
create index if not exists beca_orden_pago_estado_idx on public.beca_orden_pago (estado);

-- Una fila por línea del Anexo 02.
create table if not exists public.beca_orden_pago_detalle (
  id                    bigint generated by default as identity primary key,
  orden_pago_id         bigint not null references public.beca_orden_pago(id) on delete cascade,
  beca_id               integer not null references public.becas_nueva(id),
  concepto_id           integer not null references public.concepto_beca(id),
  periodo_academico     text,
  institucion_id        integer references public.institucion(id),
  cuenta_contable       text,
  tipo_abono            text not null check (tipo_abono in ('IE','BECARIO')),
  beneficiario_nombre   text not null,
  beneficiario_doc_tipo text not null check (beneficiario_doc_tipo in ('DNI','RUC','CE')),
  beneficiario_doc      text not null,
  banco_id              integer references public.bancos(id),
  numero_cuenta         text,
  cci                   char(20),
  monto                 numeric(14,2) not null check (monto > 0),
  comprobante_ruc_emisor text,
  comprobante_numero    text,
  comprobante_fecha     date,
  comprobante_monto     numeric(14,2),
  estado                text not null default 'PENDIENTE' check (estado in ('PENDIENTE','PAGADA','RECHAZADA','ANULADA')),
  avance_beca_id        bigint unique references public.avance_beca(id) on delete set null,
  fila_anexo            integer,
  observacion           text
);
-- Un mismo comprobante no se reembolsa dos veces.
create unique index if not exists beca_opd_comprobante_uq
  on public.beca_orden_pago_detalle (comprobante_ruc_emisor, comprobante_numero)
  where comprobante_numero is not null and estado <> 'ANULADA';
create index if not exists beca_opd_beca_idx on public.beca_orden_pago_detalle (beca_id);
create index if not exists beca_opd_orden_idx on public.beca_orden_pago_detalle (orden_pago_id);

-- Líneas que NO descuentan del saldo por concepto: pagos históricos cuyo concepto no se
-- pudo determinar (eventos de avance_beca que concentran varias OP). Siguen PAGADA y
-- enlazadas a su evento; solo quedan fuera de v_beca_saldo hasta tener el desglose.
alter table public.beca_orden_pago_detalle add column if not exists cuenta_en_saldo boolean not null default true;

-- Saldo por becario y concepto (después de crear el detalle, del que depende).
create or replace view public.v_beca_saldo as
select p.beca_id, p.concepto_id, p.programado,
       coalesce(sum(d.monto) filter (where d.estado = 'PAGADA' and d.cuenta_en_saldo), 0) as ejecutado,
       p.programado - coalesce(sum(d.monto) filter (where d.estado = 'PAGADA' and d.cuenta_en_saldo), 0) as saldo
from public.beca_presupuesto p
left join public.beca_orden_pago_detalle d
       on d.beca_id = p.beca_id and d.concepto_id = p.concepto_id
group by p.beca_id, p.concepto_id, p.programado;
